-- Schema definition for Task Management System (TMS) PostgreSQL Database

CREATE TABLE IF NOT EXISTS tms_meta (
    key   TEXT PRIMARY KEY,
    value TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS tms_users (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       TEXT NOT NULL,
    email      TEXT NOT NULL,
    password   TEXT NOT NULL,
    role       TEXT NOT NULL DEFAULT 'user'
               CHECK (role IN ('admin','manager','team member','user')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS tms_users_email_key ON tms_users (lower(email));

CREATE TABLE IF NOT EXISTS tms_tasks (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     INTEGER REFERENCES tms_users(id) ON DELETE CASCADE,
    assigned_to INTEGER REFERENCES tms_users(id) ON DELETE SET NULL,
    title       TEXT NOT NULL,
    description TEXT,
    due_date    TEXT,
    priority    TEXT,
    category    TEXT,
    status      TEXT NOT NULL DEFAULT 'pending',
    completed   BOOLEAN NOT NULL DEFAULT false,
    attachments TEXT[] NOT NULL DEFAULT '{}',
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS tms_tasks_user_idx ON tms_tasks (user_id);
CREATE INDEX IF NOT EXISTS tms_tasks_assigned_idx ON tms_tasks (assigned_to);

CREATE TABLE IF NOT EXISTS tms_comments (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id    BIGINT NOT NULL REFERENCES tms_tasks(id) ON DELETE CASCADE,
    user_id    INTEGER REFERENCES tms_users(id) ON DELETE SET NULL,
    message    TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS tms_comments_task_idx ON tms_comments (task_id);

CREATE TABLE IF NOT EXISTS tms_categories (
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS tms_categories_name_key ON tms_categories (lower(name));

CREATE TABLE IF NOT EXISTS tms_labels (
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS tms_labels_name_key ON tms_labels (lower(name));

